### ISSUE TITLE
use gfm instead of markdown_github

### ISSUE THREAD

**Issue by konradmayer** [ousmanedev/wikitopdf#1]
Dear Rahmane Ousmane, 
thanks for sharing your script and the great blog post!

It appears that now `gfm` needs to be used instead of `markdown_github`
https://github.com/ousmanedev/wikitopdf/blob/74f4c5f91e801f9d189140ae36e5d5249cd1079a/wikitopdf.sh#L20

best,
Konrad

**Comment by ousmanedev** [comment]
Hello @konradmayer 
Thank you for the kind words, and for reporting this. Would you like to make the change ?

**Comment by konradmayer** [comment]
if you like to I can open a pull request. but as its only about changing a single string it may be overkill

**Comment by ousmanedev** [comment]
Solved in this [PR](https://github.com/ousmanedev/wikitopdf/pull/3)

Closing this.
