### ISSUE TITLE
order of chapters

### ISSUE THREAD

**Issue by konradmayer** [ousmanedev/wikitopdf#2]
simply cloning the wiki does not retain the order of wiki entries and chapters are ordered alphabetically. This is no problem if wiki pages are named with a numeric prefix, but without that order is lost.

**Comment by ousmanedev** [comment]
Hello @konradmayer,
Do you mean that the chapters in the resulted pdf, should be ordered alphabetically, by their names ?

**Comment by konradmayer** [comment]
Hi @ousmanedev,

the chapters will get ordered automatically in the pdf in the current implementation. The only current way of retaining a specific order would be to name the wiki pages accordingly with a numeric prefix. It would be nice to be able to specify a specific order or to order by creation date - not sure if thats possible tough

**Comment by ousmanedev** [comment]
Well, I think that'd be a bit complex, and kind of out of scope as wiki pages in Github are shown in alphabetical order, by default.
But, feel free to submit a change.
Closing this.
